def findSolution(result):
    solution=[]
    result=result.split("\n")
    for line in result:
        if(line.find("Method Summaries")!=-1):
            break
        if(line.find("Return Value")!=-1):
            start=line.find("(")
            end=line.find(")")
            solution=line[start+1:end]
            print (float(solution))

result="""SETest_log.run(0.0)  --> Return Value: 0.0
SETest_log.run(1.0)  --> Return Value: 0.0
SETest_log.run(12.0326701798)  --> Return Value: 1.0

====================================================== Method Summaries (HTML)
<h1>Test Cases Generated by Symbolic JavaPath Finder for SETest_log.run (Path Coverage) </h1>"""
findSolution(result)